/// Dial codes for the sign-in country picker.
///
/// Generated from loyalty-dashboard/src/lib/countryCodes.ts, which is the one
/// this was copied from — transcribing 235 rows by hand is how a picker ends up
/// offering a code that does not exist. Regenerate rather than edit.
class CountryCode {
  const CountryCode(this.dial, this.flag, this.name);

  final String dial;
  final String flag;
  final String name;
}

const countryCodes = <CountryCode>[
  CountryCode('+93', '🇦🇫', 'Afghanistan'),
  CountryCode('+355', '🇦🇱', 'Albania'),
  CountryCode('+213', '🇩🇿', 'Algeria'),
  CountryCode('+1684', '🇦🇸', 'American Samoa'),
  CountryCode('+376', '🇦🇩', 'Andorra'),
  CountryCode('+244', '🇦🇴', 'Angola'),
  CountryCode('+1264', '🇦🇮', 'Anguilla'),
  CountryCode('+1268', '🇦🇬', 'Antigua and Barbuda'),
  CountryCode('+54', '🇦🇷', 'Argentina'),
  CountryCode('+374', '🇦🇲', 'Armenia'),
  CountryCode('+297', '🇦🇼', 'Aruba'),
  CountryCode('+61', '🇦🇺', 'Australia'),
  CountryCode('+43', '🇦🇹', 'Austria'),
  CountryCode('+994', '🇦🇿', 'Azerbaijan'),
  CountryCode('+1242', '🇧🇸', 'Bahamas'),
  CountryCode('+973', '🇧🇭', 'Bahrain'),
  CountryCode('+880', '🇧🇩', 'Bangladesh'),
  CountryCode('+1246', '🇧🇧', 'Barbados'),
  CountryCode('+375', '🇧🇾', 'Belarus'),
  CountryCode('+32', '🇧🇪', 'Belgium'),
  CountryCode('+501', '🇧🇿', 'Belize'),
  CountryCode('+229', '🇧🇯', 'Benin'),
  CountryCode('+1441', '🇧🇲', 'Bermuda'),
  CountryCode('+975', '🇧🇹', 'Bhutan'),
  CountryCode('+591', '🇧🇴', 'Bolivia'),
  CountryCode('+387', '🇧🇦', 'Bosnia and Herzegovina'),
  CountryCode('+267', '🇧🇼', 'Botswana'),
  CountryCode('+55', '🇧🇷', 'Brazil'),
  CountryCode('+246', '🇮🇴', 'British Indian Ocean Territory'),
  CountryCode('+1284', '🇻🇬', 'British Virgin Islands'),
  CountryCode('+673', '🇧🇳', 'Brunei'),
  CountryCode('+359', '🇧🇬', 'Bulgaria'),
  CountryCode('+226', '🇧🇫', 'Burkina Faso'),
  CountryCode('+257', '🇧🇮', 'Burundi'),
  CountryCode('+855', '🇰🇭', 'Cambodia'),
  CountryCode('+237', '🇨🇲', 'Cameroon'),
  CountryCode('+1', '🇨🇦', 'Canada'),
  CountryCode('+238', '🇨🇻', 'Cape Verde'),
  CountryCode('+1345', '🇰🇾', 'Cayman Islands'),
  CountryCode('+236', '🇨🇫', 'Central African Republic'),
  CountryCode('+235', '🇹🇩', 'Chad'),
  CountryCode('+56', '🇨🇱', 'Chile'),
  CountryCode('+86', '🇨🇳', 'China'),
  CountryCode('+61', '🇨🇽', 'Christmas Island'),
  CountryCode('+57', '🇨🇴', 'Colombia'),
  CountryCode('+269', '🇰🇲', 'Comoros'),
  CountryCode('+242', '🇨🇬', 'Congo'),
  CountryCode('+243', '🇨🇩', 'Congo (DRC)'),
  CountryCode('+682', '🇨🇰', 'Cook Islands'),
  CountryCode('+506', '🇨🇷', 'Costa Rica'),
  CountryCode('+385', '🇭🇷', 'Croatia'),
  CountryCode('+53', '🇨🇺', 'Cuba'),
  CountryCode('+599', '🇨🇼', 'Curaçao'),
  CountryCode('+357', '🇨🇾', 'Cyprus'),
  CountryCode('+420', '🇨🇿', 'Czech Republic'),
  CountryCode('+45', '🇩🇰', 'Denmark'),
  CountryCode('+253', '🇩🇯', 'Djibouti'),
  CountryCode('+1767', '🇩🇲', 'Dominica'),
  CountryCode('+1809', '🇩🇴', 'Dominican Republic'),
  CountryCode('+593', '🇪🇨', 'Ecuador'),
  CountryCode('+20', '🇪🇬', 'Egypt'),
  CountryCode('+503', '🇸🇻', 'El Salvador'),
  CountryCode('+240', '🇬🇶', 'Equatorial Guinea'),
  CountryCode('+291', '🇪🇷', 'Eritrea'),
  CountryCode('+372', '🇪🇪', 'Estonia'),
  CountryCode('+268', '🇸🇿', 'Eswatini'),
  CountryCode('+251', '🇪🇹', 'Ethiopia'),
  CountryCode('+500', '🇫🇰', 'Falkland Islands'),
  CountryCode('+298', '🇫🇴', 'Faroe Islands'),
  CountryCode('+679', '🇫🇯', 'Fiji'),
  CountryCode('+358', '🇫🇮', 'Finland'),
  CountryCode('+33', '🇫🇷', 'France'),
  CountryCode('+594', '🇬🇫', 'French Guiana'),
  CountryCode('+689', '🇵🇫', 'French Polynesia'),
  CountryCode('+241', '🇬🇦', 'Gabon'),
  CountryCode('+220', '🇬🇲', 'Gambia'),
  CountryCode('+995', '🇬🇪', 'Georgia'),
  CountryCode('+49', '🇩🇪', 'Germany'),
  CountryCode('+233', '🇬🇭', 'Ghana'),
  CountryCode('+350', '🇬🇮', 'Gibraltar'),
  CountryCode('+30', '🇬🇷', 'Greece'),
  CountryCode('+299', '🇬🇱', 'Greenland'),
  CountryCode('+1473', '🇬🇩', 'Grenada'),
  CountryCode('+590', '🇬🇵', 'Guadeloupe'),
  CountryCode('+1671', '🇬🇺', 'Guam'),
  CountryCode('+502', '🇬🇹', 'Guatemala'),
  CountryCode('+224', '🇬🇳', 'Guinea'),
  CountryCode('+245', '🇬🇼', 'Guinea-Bissau'),
  CountryCode('+592', '🇬🇾', 'Guyana'),
  CountryCode('+509', '🇭🇹', 'Haiti'),
  CountryCode('+504', '🇭🇳', 'Honduras'),
  CountryCode('+852', '🇭🇰', 'Hong Kong'),
  CountryCode('+36', '🇭🇺', 'Hungary'),
  CountryCode('+354', '🇮🇸', 'Iceland'),
  CountryCode('+91', '🇮🇳', 'India'),
  CountryCode('+62', '🇮🇩', 'Indonesia'),
  CountryCode('+98', '🇮🇷', 'Iran'),
  CountryCode('+964', '🇮🇶', 'Iraq'),
  CountryCode('+353', '🇮🇪', 'Ireland'),
  CountryCode('+972', '🇮🇱', 'Israel'),
  CountryCode('+39', '🇮🇹', 'Italy'),
  CountryCode('+225', '🇨🇮', 'Ivory Coast'),
  CountryCode('+1876', '🇯🇲', 'Jamaica'),
  CountryCode('+81', '🇯🇵', 'Japan'),
  CountryCode('+962', '🇯🇴', 'Jordan'),
  CountryCode('+7', '🇰🇿', 'Kazakhstan'),
  CountryCode('+254', '🇰🇪', 'Kenya'),
  CountryCode('+686', '🇰🇮', 'Kiribati'),
  CountryCode('+383', '🇽🇰', 'Kosovo'),
  CountryCode('+965', '🇰🇼', 'Kuwait'),
  CountryCode('+996', '🇰🇬', 'Kyrgyzstan'),
  CountryCode('+856', '🇱🇦', 'Laos'),
  CountryCode('+371', '🇱🇻', 'Latvia'),
  CountryCode('+961', '🇱🇧', 'Lebanon'),
  CountryCode('+266', '🇱🇸', 'Lesotho'),
  CountryCode('+231', '🇱🇷', 'Liberia'),
  CountryCode('+218', '🇱🇾', 'Libya'),
  CountryCode('+423', '🇱🇮', 'Liechtenstein'),
  CountryCode('+370', '🇱🇹', 'Lithuania'),
  CountryCode('+352', '🇱🇺', 'Luxembourg'),
  CountryCode('+853', '🇲🇴', 'Macau'),
  CountryCode('+261', '🇲🇬', 'Madagascar'),
  CountryCode('+265', '🇲🇼', 'Malawi'),
  CountryCode('+60', '🇲🇾', 'Malaysia'),
  CountryCode('+960', '🇲🇻', 'Maldives'),
  CountryCode('+223', '🇲🇱', 'Mali'),
  CountryCode('+356', '🇲🇹', 'Malta'),
  CountryCode('+692', '🇲🇭', 'Marshall Islands'),
  CountryCode('+596', '🇲🇶', 'Martinique'),
  CountryCode('+222', '🇲🇷', 'Mauritania'),
  CountryCode('+230', '🇲🇺', 'Mauritius'),
  CountryCode('+262', '🇾🇹', 'Mayotte'),
  CountryCode('+52', '🇲🇽', 'Mexico'),
  CountryCode('+691', '🇫🇲', 'Micronesia'),
  CountryCode('+373', '🇲🇩', 'Moldova'),
  CountryCode('+377', '🇲🇨', 'Monaco'),
  CountryCode('+976', '🇲🇳', 'Mongolia'),
  CountryCode('+382', '🇲🇪', 'Montenegro'),
  CountryCode('+1664', '🇲🇸', 'Montserrat'),
  CountryCode('+212', '🇲🇦', 'Morocco'),
  CountryCode('+258', '🇲🇿', 'Mozambique'),
  CountryCode('+95', '🇲🇲', 'Myanmar'),
  CountryCode('+264', '🇳🇦', 'Namibia'),
  CountryCode('+674', '🇳🇷', 'Nauru'),
  CountryCode('+977', '🇳🇵', 'Nepal'),
  CountryCode('+31', '🇳🇱', 'Netherlands'),
  CountryCode('+687', '🇳🇨', 'New Caledonia'),
  CountryCode('+64', '🇳🇿', 'New Zealand'),
  CountryCode('+505', '🇳🇮', 'Nicaragua'),
  CountryCode('+227', '🇳🇪', 'Niger'),
  CountryCode('+234', '🇳🇬', 'Nigeria'),
  CountryCode('+683', '🇳🇺', 'Niue'),
  CountryCode('+850', '🇰🇵', 'North Korea'),
  CountryCode('+389', '🇲🇰', 'North Macedonia'),
  CountryCode('+1670', '🇲🇵', 'Northern Mariana Islands'),
  CountryCode('+47', '🇳🇴', 'Norway'),
  CountryCode('+968', '🇴🇲', 'Oman'),
  CountryCode('+92', '🇵🇰', 'Pakistan'),
  CountryCode('+680', '🇵🇼', 'Palau'),
  CountryCode('+970', '🇵🇸', 'Palestine'),
  CountryCode('+507', '🇵🇦', 'Panama'),
  CountryCode('+675', '🇵🇬', 'Papua New Guinea'),
  CountryCode('+595', '🇵🇾', 'Paraguay'),
  CountryCode('+51', '🇵🇪', 'Peru'),
  CountryCode('+63', '🇵🇭', 'Philippines'),
  CountryCode('+48', '🇵🇱', 'Poland'),
  CountryCode('+351', '🇵🇹', 'Portugal'),
  CountryCode('+1787', '🇵🇷', 'Puerto Rico'),
  CountryCode('+974', '🇶🇦', 'Qatar'),
  CountryCode('+262', '🇷🇪', 'Réunion'),
  CountryCode('+40', '🇷🇴', 'Romania'),
  CountryCode('+7', '🇷🇺', 'Russia'),
  CountryCode('+250', '🇷🇼', 'Rwanda'),
  CountryCode('+590', '🇧🇱', 'Saint Barthélemy'),
  CountryCode('+290', '🇸🇭', 'Saint Helena'),
  CountryCode('+1869', '🇰🇳', 'Saint Kitts and Nevis'),
  CountryCode('+1758', '🇱🇨', 'Saint Lucia'),
  CountryCode('+590', '🇲🇫', 'Saint Martin'),
  CountryCode('+508', '🇵🇲', 'Saint Pierre and Miquelon'),
  CountryCode('+1784', '🇻🇨', 'Saint Vincent and the Grenadines'),
  CountryCode('+685', '🇼🇸', 'Samoa'),
  CountryCode('+378', '🇸🇲', 'San Marino'),
  CountryCode('+239', '🇸🇹', 'São Tomé and Príncipe'),
  CountryCode('+966', '🇸🇦', 'Saudi Arabia'),
  CountryCode('+221', '🇸🇳', 'Senegal'),
  CountryCode('+381', '🇷🇸', 'Serbia'),
  CountryCode('+248', '🇸🇨', 'Seychelles'),
  CountryCode('+232', '🇸🇱', 'Sierra Leone'),
  CountryCode('+65', '🇸🇬', 'Singapore'),
  CountryCode('+1721', '🇸🇽', 'Sint Maarten'),
  CountryCode('+421', '🇸🇰', 'Slovakia'),
  CountryCode('+386', '🇸🇮', 'Slovenia'),
  CountryCode('+677', '🇸🇧', 'Solomon Islands'),
  CountryCode('+252', '🇸🇴', 'Somalia'),
  CountryCode('+27', '🇿🇦', 'South Africa'),
  CountryCode('+82', '🇰🇷', 'South Korea'),
  CountryCode('+211', '🇸🇸', 'South Sudan'),
  CountryCode('+34', '🇪🇸', 'Spain'),
  CountryCode('+94', '🇱🇰', 'Sri Lanka'),
  CountryCode('+249', '🇸🇩', 'Sudan'),
  CountryCode('+597', '🇸🇷', 'Suriname'),
  CountryCode('+47', '🇸🇯', 'Svalbard and Jan Mayen'),
  CountryCode('+46', '🇸🇪', 'Sweden'),
  CountryCode('+41', '🇨🇭', 'Switzerland'),
  CountryCode('+963', '🇸🇾', 'Syria'),
  CountryCode('+886', '🇹🇼', 'Taiwan'),
  CountryCode('+992', '🇹🇯', 'Tajikistan'),
  CountryCode('+255', '🇹🇿', 'Tanzania'),
  CountryCode('+66', '🇹🇭', 'Thailand'),
  CountryCode('+670', '🇹🇱', 'Timor-Leste'),
  CountryCode('+228', '🇹🇬', 'Togo'),
  CountryCode('+690', '🇹🇰', 'Tokelau'),
  CountryCode('+676', '🇹🇴', 'Tonga'),
  CountryCode('+1868', '🇹🇹', 'Trinidad and Tobago'),
  CountryCode('+216', '🇹🇳', 'Tunisia'),
  CountryCode('+90', '🇹🇷', 'Turkey'),
  CountryCode('+993', '🇹🇲', 'Turkmenistan'),
  CountryCode('+1649', '🇹🇨', 'Turks and Caicos Islands'),
  CountryCode('+688', '🇹🇻', 'Tuvalu'),
  CountryCode('+1340', '🇻🇮', 'U.S. Virgin Islands'),
  CountryCode('+256', '🇺🇬', 'Uganda'),
  CountryCode('+380', '🇺🇦', 'Ukraine'),
  CountryCode('+971', '🇦🇪', 'UAE'),
  CountryCode('+44', '🇬🇧', 'United Kingdom'),
  CountryCode('+1', '🇺🇸', 'United States'),
  CountryCode('+598', '🇺🇾', 'Uruguay'),
  CountryCode('+998', '🇺🇿', 'Uzbekistan'),
  CountryCode('+678', '🇻🇺', 'Vanuatu'),
  CountryCode('+379', '🇻🇦', 'Vatican City'),
  CountryCode('+58', '🇻🇪', 'Venezuela'),
  CountryCode('+84', '🇻🇳', 'Vietnam'),
  CountryCode('+681', '🇼🇫', 'Wallis and Futuna'),
  CountryCode('+967', '🇾🇪', 'Yemen'),
  CountryCode('+260', '🇿🇲', 'Zambia'),
  CountryCode('+263', '🇿🇼', 'Zimbabwe'),
];
